// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdlrykoeyrrhonnwywgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkbHJ5a29leXJyaG9ubnd5d2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NjE5NjIsImV4cCI6MjA1NDIzNzk2Mn0.oSpLYTb1x2f2rRg_lHa1pB-xIdZu83X8Kpndc688RG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);